package blackbox;

public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProfileLeft = new javax.swing.JPanel();
        generic_icon = new javax.swing.JLabel();
        FullNameScrollPane = new javax.swing.JScrollPane();
        FullName = new javax.swing.JTextArea();
        UsernameScrollPane = new javax.swing.JScrollPane();
        Username = new javax.swing.JTextArea();
        BackToConversation = new javax.swing.JButton();
        ProfileRight = new javax.swing.JPanel();
        BiographyScrollPane = new javax.swing.JScrollPane();
        Biography = new javax.swing.JTextArea();
        BiographyLabel = new javax.swing.JLabel();
        RSAScrollPane = new javax.swing.JScrollPane();
        RSAKey = new javax.swing.JTextArea();
        RSALabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        ProfileLeft.setBackground(new java.awt.Color(0, 0, 0));
        ProfileLeft.setPreferredSize(new java.awt.Dimension(400, 500));

        generic_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generic_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_picture.png"))); // NOI18N
        generic_icon.setText("jLabel2");

        FullNameScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        FullNameScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        FullName.setEditable(false);
        FullName.setBackground(new java.awt.Color(0, 0, 0));
        FullName.setColumns(20);
        FullName.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 255, 255));
        FullName.setRows(1);
        FullNameScrollPane.setViewportView(FullName);

        UsernameScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        UsernameScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Username.setEditable(false);
        Username.setBackground(new java.awt.Color(0, 0, 0));
        Username.setColumns(20);
        Username.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setRows(1);
        UsernameScrollPane.setViewportView(Username);

        BackToConversation.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BackToConversation.setForeground(new java.awt.Color(0, 48, 107));
        BackToConversation.setText("Back");
        BackToConversation.setIconTextGap(0);
        BackToConversation.setMargin(new java.awt.Insets(2, 14, 0, 14));
        BackToConversation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToConversationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileLeftLayout = new javax.swing.GroupLayout(ProfileLeft);
        ProfileLeft.setLayout(ProfileLeftLayout);
        ProfileLeftLayout.setHorizontalGroup(
            ProfileLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLeftLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(ProfileLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLeftLayout.createSequentialGroup()
                        .addGroup(ProfileLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullNameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLeftLayout.createSequentialGroup()
                        .addComponent(generic_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(ProfileLeftLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BackToConversation, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProfileLeftLayout.setVerticalGroup(
            ProfileLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLeftLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(BackToConversation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generic_icon)
                .addGap(30, 30, 30)
                .addComponent(UsernameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FullNameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(ProfileLeft);
        ProfileLeft.setBounds(0, 0, 400, 500);

        ProfileRight.setBackground(new java.awt.Color(255, 255, 255));
        ProfileRight.setPreferredSize(new java.awt.Dimension(400, 500));

        BiographyScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        BiographyScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Biography.setEditable(false);
        Biography.setBackground(new java.awt.Color(255, 255, 255));
        Biography.setColumns(50);
        Biography.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        Biography.setForeground(new java.awt.Color(255, 255, 255));
        Biography.setRows(20);
        BiographyScrollPane.setViewportView(Biography);

        BiographyLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        BiographyLabel.setForeground(new java.awt.Color(0, 48, 107));
        BiographyLabel.setText("Biography");

        RSAScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RSAScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        RSAKey.setEditable(false);
        RSAKey.setBackground(new java.awt.Color(255, 255, 255));
        RSAKey.setColumns(50);
        RSAKey.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        RSAKey.setForeground(new java.awt.Color(255, 255, 255));
        RSAKey.setRows(1);
        RSAScrollPane.setViewportView(RSAKey);

        RSALabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        RSALabel.setForeground(new java.awt.Color(0, 48, 107));
        RSALabel.setText("Public RSA Key");

        javax.swing.GroupLayout ProfileRightLayout = new javax.swing.GroupLayout(ProfileRight);
        ProfileRight.setLayout(ProfileRightLayout);
        ProfileRightLayout.setHorizontalGroup(
            ProfileRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileRightLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(ProfileRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileRightLayout.createSequentialGroup()
                        .addGroup(ProfileRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BiographyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RSAScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileRightLayout.createSequentialGroup()
                        .addComponent(BiographyLabel)
                        .addGap(144, 144, 144))))
            .addGroup(ProfileRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileRightLayout.createSequentialGroup()
                    .addContainerGap(135, Short.MAX_VALUE)
                    .addComponent(RSALabel)
                    .addGap(117, 117, 117)))
        );
        ProfileRightLayout.setVerticalGroup(
            ProfileRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileRightLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(RSAScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(BiographyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BiographyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(ProfileRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProfileRightLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(RSALabel)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );

        jPanel1.add(ProfileRight);
        ProfileRight.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToConversationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToConversationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackToConversationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToConversation;
    private javax.swing.JTextArea Biography;
    private javax.swing.JLabel BiographyLabel;
    private javax.swing.JScrollPane BiographyScrollPane;
    private javax.swing.JTextArea FullName;
    private javax.swing.JScrollPane FullNameScrollPane;
    private javax.swing.JPanel ProfileLeft;
    private javax.swing.JPanel ProfileRight;
    private javax.swing.JTextArea RSAKey;
    private javax.swing.JLabel RSALabel;
    private javax.swing.JScrollPane RSAScrollPane;
    private javax.swing.JTextArea Username;
    private javax.swing.JScrollPane UsernameScrollPane;
    private javax.swing.JLabel generic_icon;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
